export const GET_COCKTAILS_SUCCESS = 'GET_COCKTAILS_SUCCESS';
export const GET_COCKTAILS_FAIL = 'GET_COCKTAILS_FAIL';
export const GET_COCKTAILS_IN_PROGRESS = 'GET_COCKTAILS_IN_PROGRESS';

export const GET_COCKTAIL_SUCCESS = 'GET_COCKTAIL_SUCCESS';
export const GET_COCKTAIL_FAIL = 'GET_COCKTAIL_FAIL';
export const GET_COCKTAIL_IN_PROGRESS = 'GET_COCKTAIL_IN_PROGRESS';

export const CHANGE_FILTER = 'CHANGE_FILTER';
